version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - rest_backend
      - webhook_backend

  rest_backend:
    build: ./rest_backend
    ports:
      - "5000:5000"

  webhook_backend:
    build: ./webhook_backend
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
